In [9]:
import numpy as np

# faster for factorization
a =np.array([1,2,3,100])
b = np.array([5,6,7,8])

# addition
add = a+b  # elemrnt position wise addition
print(add)




[  6   8  10 108]


In [10]:
# mathematical function 

# trigonometry
# sin , cos, tan takes values in radian
sin_val = np.sin(a)  
print(sin_val)

# radian to degree
deg_conversion = np.rad2deg(a)
print(deg_conversion)

[ 0.84147098  0.90929743  0.14112001 -0.50636564]
[  57.29577951  114.59155903  171.88733854 5729.57795131]


In [13]:
# log

base_10_log_val = np.log10(a)  # it represents how much time we can devide a val 
                                # ex. 100/10 = 10  , 10/10 =1  ans is 2
print(base_10_log_val)

sqrt = np.sqrt(a)
print(sqrt)

[0.         0.30103    0.47712125 2.        ]
[ 1.          1.41421356  1.73205081 10.        ]


In [16]:
# different types

# cumulative sum
cumul = np.cumulative_sum(a)  # por por + kore agaite thakbe
print(cumul)

[  1   3   6 106]
