# Array Manipulation

In [1]:
import numpy as np

arr = np.random.randint(1,100 , size =(10,5))

In [2]:
arr.shape

(10, 5)

In [12]:
b = arr.reshape(5,10)
b.shape
b.ndim
b

array([[24, 16, 60, 83, 87, 11, 80, 35, 78, 15],
       [34, 28, 95, 30, 57, 58, 88, 87, 94, 81],
       [99, 94, 34,  9, 89, 66, 84, 71, 57, 31],
       [33, 31, 82, 50,  3, 62, 64, 38, 77, 23],
       [95, 58, 97, 29, 43, 18, 59, 55, 30, 58]], dtype=int32)

In [17]:
# changing to 1D from any shape 
flatten = b.flatten()
print(flatten)

print(flatten.ndim)  # row wise flattening

column_wise_flattening = np.ravel(b,order = "F")
row_wise_flattening = np.ravel(b,order = "C")
print(column_wise_flattening)
print(row_wise_flattening)


[24 16 60 83 87 11 80 35 78 15 34 28 95 30 57 58 88 87 94 81 99 94 34  9
 89 66 84 71 57 31 33 31 82 50  3 62 64 38 77 23 95 58 97 29 43 18 59 55
 30 58]
1
[24 34 99 33 95 16 28 94 31 58 60 95 34 82 97 83 30  9 50 29 87 57 89  3
 43 11 58 66 62 18 80 88 84 64 59 35 87 71 38 55 78 94 57 77 30 15 81 31
 23 58]
[24 16 60 83 87 11 80 35 78 15 34 28 95 30 57 58 88 87 94 81 99 94 34  9
 89 66 84 71 57 31 33 31 82 50  3 62 64 38 77 23 95 58 97 29 43 18 59 55
 30 58]


In [20]:

a = np.random.randint(1,10 , size =(2,3))
b = np.random.randint(20,30 , size =(2,3))




### Concatenate

In [23]:
con = np.concatenate((a,b), axis = 0) # row wise
print(con)

con = np.concatenate((a,b), axis = 1) # column wise
print(con)

[[ 1  5  3]
 [ 8  6  6]
 [25 27 21]
 [20 23 23]]
[[ 1  5  3 25 27 21]
 [ 8  6  6 20 23 23]]


In [29]:
# error

# row wise concatenate korar somoi column same thakte hobe
# column wise concatenate korar somoi row same thakte hobe


a = np.random.randint(1,10 , size =(2,3))
b = np.random.randint(20,30 , size =(1,3))


r = np.concatenate((a,b) ,axis = 0)  #it runs perfectly
# r = np.concatenate((a,b) ,axis = 1)  #it don't run perfectly
print(r)

[[ 5  6  8]
 [ 9  4  2]
 [26 20 22]]


### Transpose mat

In [32]:
mat = np.array([[1,2,3],
              [4,5,6]
             ])
trans = mat.T
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [42]:
# array Split


a = np.random.randint(1,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,2)
print(splitted_array)


[9 2 4 6 1 1 7 2 9 6]
[array([9, 2, 4, 6, 1], dtype=int32), array([1, 7, 2, 9, 6], dtype=int32)]
