## inplace sorting

In [3]:
# once sorted we can't get back the previous unsorted one
import numpy as np
x = np.array([10,34,4,42,12])

z = x.copy()
print(z)

z.sort()

print(z)


[10 34  4 42 12]
[ 4 10 12 34 42]


## Copy sorting

In [5]:
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[ 4 10 12 34 42]
[10 34  4 42 12]


## 2D array sorting


In [7]:
mat = np.array([[10,3,5],[8,4,9]])

# horizontally axis = 1
hor_sort = np.sort(mat,axis = 1)
print(hor_sort)
# horizontally axis = 1
hor_sort = np.sort(mat,axis = 1)
print(hor_sort)

[[ 3  5 10]
 [ 4  8  9]]
