In [4]:
import numpy as np
x = np.array([10,34,4,42,12])

# np.where
index = np.where(x==4)
print(index)


index = np.where(x>14)
print(index)

# np.where(condition , x, y) if true x, otherwise replace with y
arr = np.where(x>14 , x, 0)
print(arr)


(array([2]),)
(array([1, 3]),)
[ 0 34  0 42  0]


In [5]:
mat = np.array([[10,3,5],[8,4,9]])
index = np.where(mat==4)  
print(index)

(array([1]), array([1]))


In [9]:
# finding the maximum value from array

max_index = np.argmax(x)  # returns index
min_index = np.argmin(x)  # returns index
print(max_index)
print(min_index)

3
2


##  Counting

In [2]:
import numpy as np
a = np.random.randint(1,100, size=(100,))
print(a)

[75 95 32 27 31 22 62 23 53 36 20 64 88 24 87 54 60 58 27 82 91 14 83 46
 57 54 13 17 60 42 86 22 48 74 39 78 46 54 80  8 56 20 15 71 40 79 33 22
 66  3 48 98 87 88 35 46 37 50 33 69 87 27 48 68  9 19 20 37 12 39 50 60
 11 13 23 84 56 24 78 15 35 87 60 94 69 17  6 89 83 32 63 83 14  3 78 44
 16 35 56 54]


In [5]:
value_great_than_60 = np.count_nonzero(a>40)  #(condition)
print(value_great_than_60)

56


In [14]:
# finding unique values
unique_vals = np.unique(a)

# this returns kon unique value koibar ache
unique_vals = np.unique(a, return_counts = True)
print(unique_vals)

(array([ 3,  6,  8,  9, 11, 12, 13, 14, 15, 16, 17, 19, 20, 22, 23, 24, 27,
       31, 32, 33, 35, 36, 37, 39, 40, 42, 44, 46, 48, 50, 53, 54, 56, 57,
       58, 60, 62, 63, 64, 66, 68, 69, 71, 74, 75, 78, 79, 80, 82, 83, 84,
       86, 87, 88, 89, 91, 94, 95, 98], dtype=int32), array([2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 3, 3, 2, 2, 3, 1, 2, 2, 3, 1,
       2, 2, 1, 1, 1, 3, 3, 2, 1, 4, 3, 1, 1, 4, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 3, 1, 1, 1, 3, 1, 1, 4, 2, 1, 1, 1, 1, 1]))
