In [9]:
# Data load
import numpy as np
data = np.genfromtxt("result.csv", delimiter=',', skip_header =1)
print(data)

[[67. 90. 69.]
 [34. 87. 65.]
 [54. 76. 90.]
 [23. 56. 76.]
 [78. 92. 57.]
 [98. 93. 94.]
 [78. 86. 64.]
 [67. 88. 70.]
 [87. 99. 59.]
 [67. 98. 45.]
 [45. 95. 38.]
 [95. 64. 95.]
 [75. 87. 43.]
 [43. 34. 78.]
 [98. 87. 45.]
 [56. 34. 78.]
 [43. 78. 93.]
 [91. 94. 95.]
 [82. 48. 53.]
 [85. 60. 86.]]


In [14]:
# statistics
math_marks = data[:: , :1]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

max_math_marks = np.mean(math_marks)
print(max_math_marks)

# standard daviation
std_math_marks= np.std(math_marks)
print(std_math_marks)

[[67. 34. 54. 23. 78. 98. 78. 67. 87. 67. 45. 95. 75. 43. 98. 56. 43. 91.
  82. 85.]]
98.0
68.3
21.741895041601133
