In [5]:
import numpy as np

# np.arange( start, end, step) -> similar to range function

arr = np.arange(1,10,1).reshape(3,3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [9]:
# np.linspace(start , end, koita)
# points will be in each same distance

arr = np.linspace(1,10,11)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
<class 'numpy.ndarray'>
float64
(11,)
1
11


In [13]:
# np.logspace(start , end, koita)
# points will not be in each same distance

arr = np.logspace(1,4,5)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]
<class 'numpy.ndarray'>
float64
(5,)
1
5
