In [4]:
import numpy as np
lis = [10,20,30,40.3]

arr = np.array(lis, dtype = np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40]
<class 'numpy.ndarray'>
int32


In [6]:
matrix = [[1,2,3,4],
          [2,4,5,7]]
arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)



[[1 2 3 4]
 [2 4 5 7]]
<class 'numpy.ndarray'>
int64
2
(2, 4)


In [2]:
# tupple 
import numpy as np
tup = (10,20,30)
arr = np.array(tup, dtype = np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[10 20 30]
<class 'numpy.ndarray'>
int32
1
(3,)


In [3]:
# set

set = {10,20,30}
arr = np.array(set)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

{10, 20, 30}
<class 'numpy.ndarray'>
object
0
()


In [12]:
dic = {'a':10 , 'b':20}
keys = dic.keys()
print(keys)
print(dic.values())

# keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim) 
print(arr.shape)

print("\n")

# values to ndarray
values = dic.values()
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim) 
print(arr.shape)

print("\n")

# items to ndarray
items = dic.items()
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim) 
print(arr.shape)


dict_keys(['a', 'b'])
dict_values([10, 20])
['a' 'b']
<class 'numpy.ndarray'>
<U1
1
(2,)


[10 20]
<class 'numpy.ndarray'>
int64
1
(2,)


[['a' '10']
 ['b' '20']]
<class 'numpy.ndarray'>
<U21
2
(2, 2)
