In [2]:
# creating diagonal matrix
import numpy as np
dia_mat = np.diag([1,2,3])
print(dia_mat)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [4]:
# identity matrix
identity_mat = np.eye(4)
print(identity_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Indexing and slicing

In [10]:
#2D slicing
# arr[row_start : row_end : step , column_start : column_end : step]

print(dia_mat)

# getting a row
row_0 = dia_mat[0:1 , ]
print(row_0)

# getting a column
col_0 = dia_mat[:: , 0:1]
print(col_0)



# getting a portion
portion = dia_mat[:: , 0:2]
print(portion)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0]]
[[1]
 [0]
 [0]]
[[1 0]
 [0 2]
 [0 0]]


# Advanced indexing

In [27]:
lis = np.array([1,2,3,4,5,6])
values = lis[[2,4]]  #lis[[index]]
print(values)

mat = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

print(mat[[0,1] , [1,2]])

print(mat[mat>2])


for i in np.nditer(mat):
    print(i)

[3 5]
[2 6]
[3 4 5 6 7 8 9]
1
2
3
4
5
6
7
8
9
