   ## Array creation with random values

In [4]:
import numpy as np
 # np.random.rand(shape)

arr = np.random.rand(2,3) # 0 to 1 values

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.48329678 0.83508044 0.19245547]
 [0.21545188 0.55408241 0.14957963]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [13]:
 # np.random.randint(start,end , shape)

arr = np.random.randint(1,10,(10,10)) # 1 to 10 values
                    # 1 -> 10 th values (row,column)
# creating 1D array
# arr = np.random.randint(1,10,(2,)) # 1 to 10 values
#                     # 1 -> 10 th values (row,column)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 8 4 8 8 1 4 8 4 1]
 [2 9 1 6 7 3 2 9 6 1]
 [3 5 6 1 5 6 3 7 8 5]
 [5 4 2 7 6 7 5 1 4 1]
 [3 4 9 3 9 8 8 9 7 5]
 [8 6 3 7 9 2 4 8 6 8]
 [5 1 6 2 2 2 2 9 5 9]
 [2 3 7 5 2 2 1 9 4 1]
 [6 4 3 3 4 5 5 5 9 9]
 [3 2 4 8 7 1 8 5 7 2]]
<class 'numpy.ndarray'>
int32
(10, 10)
2
100


In [16]:
 # np.random.uniform(start,end , shape)

arr = np.random.uniform(10,20,(2,3)) # 10 to 20 values
                    # 10 -> 20 th values (row,column)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[13.59017468 11.11260748 10.25160131]
 [17.97085462 11.4961506  10.30969707]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6
