In [2]:
#np.zeros
import numpy as np
arr = np.zeros((3,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim) 
print(arr.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(3, 3)
2
9


In [4]:
# np.zeros_like

arr3 = np.array([[[1,2,3,4],
                 [2,4,5,7] ],
                 
                [[1,2,3,4],
                 [2,4,5,7] ],
                
                [[1,2,3,4],
                 [2,4,5,7] ],
                ])

arr = np.zeros_like(arr3)
print(arr)
print(arr.shape)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
(3, 2, 4)


In [7]:
# np.ones

arr = np.ones((2,3,3) , dtype = np.int8)
            # 2segment 3rows 3columns
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim) 
print(arr.size)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(2, 3, 3)
3
18


In [13]:
# np.empty
# this generates random numbered array
arr = np.empty((2,3), dtype = np.int8)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim) 
print(arr.size)

[[-2 -1 -1]
 [-1  0  0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6


In [14]:
# np.full

arr = np.full((2,3), 10)
      # 2rows 3columns  and filled with which value
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim) 
print(arr.size)

[[10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6
